### PR TITLE
Feature/gitignore

### PR DESCRIPTION
**Pull request by thomas-j-sell**
I added a gitignore file.  This will prevent git from picking up all the unity fluff that doesn't need to be included in version control.

### CODE REVIEW

**Comment by Haden2** [comment]
Can you explain gitignore? And also if I need to do anything. Because it says you are requesting a merge. Do I need to click Merge Pull Request?

**Comment by thomas-j-sell** [comment]
Gitignore is a file that tells git the type of files in the repository that git should not track.  For example .DS_Store files are hidden files that tell OS X how to arrange files in a finder window.  These have nothing to do with the project so they don’t need to be tracked by git.  Unity generates a crapton (that’s a technical term) of unnecessary-to-track files.  Keeping these files outside of git simplifies managing the repository, and prevents OS specific files from causing problems on other systems.  You can find more information about it and how it works by following the link I sent.  

A pull request does require action on your part.  I recommend you read up on git and github before you complete the pull request so you understand what it’s doing.  The short version is that a pull request is a request for you to review my changes and either accept or reject them.  

## 

Thomas Sell

**Comment by Haden2** [comment]
If I understood the tutorial, you basically just took a separate branch from the master branch and requested that they get put together. Having them separate is a way to test things out on its own so it does not interfere with the main branch.

**Comment by thomas-j-sell** [comment]
Pretty much.  Branching is the main strength of git.  It allows you to experiment without fear of breaking things.

## 

Thomas Sell

**Comment by Haden2** [comment]
That is good because it is going to take a lot of testing to get the
different kind of visions right.

**Pull request merged**
